swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: (Referentiel) Etat adhesion
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ref_etat_adhesion:
    get:
      description: |
        Returns all etats adhesions from the system that the user has access to 
      operationId: findEtatAdhesion
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: etat adhesion response
          schema:
            type: array
            items:
              $ref: '#/definitions/EtatAdhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new etat adhesion.
      operationId: addEtatUsager
      parameters:
        - name: etat adhesion
          in: body
          description: EtatUsager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewEtatAdhesion'
      responses:
        200:
          description: etat adhesion response
          schema:
            $ref: '#/definitions/EtatAdhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /ref_etat_adhesion/{id_etat_adhesion}:
    get:
      description: Returns an etat adhesion based on a single ID
      operationId: find etat adhesion by id_etat_adhesion
      parameters:
        - name: id_etat_adhesion
          in: path
          description: ID of etat usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: adhesion response
          schema:
            $ref: '#/definitions/EtatAdhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single etat adhesion based on the ID supplied
      operationId: deleteEtatUsager by id_etat_adhesion
      parameters:
        - name: id_etat_adhesion
          in: path
          description: ID of etat adhesion to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: etat adhesion deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  EtatAdhesion:
    allOf:
      - $ref: '#/definitions/NewEtatAdhesion'
      - required:
        - id_etat_adhesion
        properties:
          id_etat_adhesion:
            type: integer
            format: int64
  NewEtatAdhesion:
    properties:
      libelle_etat_adhesion:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string