swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: (Referentiel) Etat demande
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ref_etat_demande:
    get:
      description: |
        Returns all etats demandes from the system that the user has access to 
      operationId: findEtatDemande
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: etat demande response
          schema:
            type: array
            items:
              $ref: '#/definitions/EtatDemande'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new etat demande.
      operationId: addEtatUsager
      parameters:
        - name: etat demande
          in: body
          description: EtatUsager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewEtatDemande'
      responses:
        200:
          description: etat demande response
          schema:
            $ref: '#/definitions/EtatDemande'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /ref_etat_demande/{id_etat_demande}:
    get:
      description: Returns an etat demande based on a single ID
      operationId: find etat demande by id_etat_demande
      parameters:
        - name: id_etat_demande
          in: path
          description: ID of etat usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: demande response
          schema:
            $ref: '#/definitions/EtatDemande'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single etat demande based on the ID supplied
      operationId: deleteEtatUsager by id_etat_demande
      parameters:
        - name: id_etat_demande
          in: path
          description: ID of etat demande to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: etat demande deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  EtatDemande:
    allOf:
      - $ref: '#/definitions/NewEtatDemande'
      - required:
        - id_etat_demande
        properties:
          id_etat_demande:
            type: integer
            format: int64
  NewEtatDemande:
    properties:
      libelle_etat_demande:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string