swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Agent
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /agent:
    get:
      description: |
        Returns all agents from the system that the user has access to 
      operationId: findUsager
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: agent response
          schema:
            type: array
            items:
              $ref: '#/definitions/Agent'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new agent.
      operationId: addAgent
      parameters:
        - name: agent
          in: body
          description: Usager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewAgent'
      responses:
        200:
          description: agent response
          schema:
            $ref: '#/definitions/Agent'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Agent:
    allOf:
      - $ref: '#/definitions/NewAgent'
      - required:
        - id_agent
        properties:
          id_agent:
            type: integer
            format: int64
  NewAgent:
    properties:
      id_CUT_agent:
        type: integer
        format: int64
      nom_agent:
        type: string
      prenom_agent:
        type: string
      adresse_email_agent:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string