swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Usager
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /usager:
    get:
      description: |
        Returns all usagers from the system that the user has access to 
      operationId: findUsager
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: usager response
          schema:
            type: array
            items:
              $ref: '#/definitions/Usager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new usager.
      operationId: addUsager
      parameters:
        - name: usager
          in: body
          description: Usager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewUsager'
      responses:
        200:
          description: usager response
          schema:
            $ref: '#/definitions/Usager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /usager/{id_usager}:
    get:
      description: Returns a user based on a single ID, if the user does not have access to the usager
      operationId: find usager by id_usager
      parameters:
        - name: id_usager
          in: path
          description: ID of usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: usager response
          schema:
            $ref: '#/definitions/Usager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single usager based on the ID supplied
      operationId: deleteUsager by id_usager
      parameters:
        - name: id_usager
          in: path
          description: ID of usager to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: usager deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Usager:
    allOf:
      - $ref: '#/definitions/NewUsager'
      - required:
        - id_usager
        properties:
          id_usager:
            type: integer
            format: int64
  NewUsager:
    properties:
      id_CUT_usager:
        type: integer
        format: int64
      nom_usager:
        type: string
      prenom_usager:
        type: string
      adresse_email_usager:
        type: string
      sexe_usager:
        type: string
      date_naissance_usager:
        type: string
      lieu_naissance_usager:
        type: string
      pays_naissance_usager:
        type: string
      nom_usage_usager:
        type: string
      adresse_postale_usager:
        type: string
      numero_telephone_usager:
        type: string
      personne_morale:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string