swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Historique Adhesion
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /historique_adhesion:
    get:
      description: |
        Returns all historique adhesions from the system that the user has access to 
      operationId: findHistoriqueAdhesion
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: demande historique adhesion response
          schema:
            type: array
            items:
              $ref: '#/definitions/HistoriqueAdhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new historique adhesion.
      operationId: addHistoriqueAdhesion
      parameters:
        - name: demande historique adhesion
          in: body
          description: HistoriqueAdhesionto add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewHistoriqueAdhesion'
      responses:
        200:
          description: demande support response
          schema:
            $ref: '#/definitions/HistoriqueAdhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /historique adhesion/{id_ha}:
    get:
      description: Returns an historique adhesion support based on a single ID
      operationId: find historique adhesion by id_ha
      parameters:
        - name: id_ha
          in: path
          description: ID of historique adhesion to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: historique adhesion response
          schema:
            $ref: '#/definitions/HistoriqueAdhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single historique adhesion based on the ID supplied
      operationId: deleteHistoriqueAdhesion by id_ha
      parameters:
        - name: id_ha
          in: path
          description: ID of historique adhesion to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: historique adhesion deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  HistoriqueAdhesion:
    allOf:
      - $ref: '#/definitions/NewHistoriqueAdhesion'
      - required:
        - id_ha
        properties:
          id_ha:
            type: integer
            format: int64
  NewHistoriqueAdhesion:
    properties:
      id_adhesion_ha:
        type: integer
        format: int64
      date_adhesion_ha:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string