swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Historique Support
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /historique_support:
    get:
      description: |
        Returns all historique supports from the system that the user has access to 
      operationId: findHistoriqueSupport
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: historique support response
          schema:
            type: array
            items:
              $ref: '#/definitions/HistoriqueSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new historique support.
      operationId: addHistoriqueSupport
      parameters:
        - name: historique support
          in: body
          description: HistoriqueSupport to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewHistoriqueSupport'
      responses:
        200:
          description: support response
          schema:
            $ref: '#/definitions/HistoriqueSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /historique_support/{id_hs}:
    get:
      description: Returns an historique support based on a single ID
      operationId: find historique support by id_hs
      parameters:
        - name: id_hs
          in: path
          description: ID of historique support to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: historique support response
          schema:
            $ref: '#/definitions/HistoriqueSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single historique support based on the ID supplied
      operationId: deleteHistoriqueSupport by id_hs
      parameters:
        - name: id_hs
          in: path
          description: ID of historique support to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: historique support deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  HistoriqueSupport:
    allOf:
      - $ref: '#/definitions/NewHistoriqueSupport'
      - required:
        - id_hs
        properties:
          id_hs:
            type: integer
            format: int64
  NewHistoriqueSupport:
    properties:
      date_hs:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string