swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: (Referentiel) Type support
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ref_type_support:
    get:
      description: |
        Returns all types supports from the system that the user has access to 
      operationId: findTypeSupport
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: type support response
          schema:
            type: array
            items:
              $ref: '#/definitions/TypeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new type support.
      operationId: addTypeUsager
      parameters:
        - name: type support
          in: body
          description: TypeUsager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewTypeSupport'
      responses:
        200:
          description: type support response
          schema:
            $ref: '#/definitions/TypeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /ref_type_support/{id_type_support}:
    get:
      description: Returns an type support based on a single ID
      operationId: find type support by id_type_support
      parameters:
        - name: id_type_support
          in: path
          description: ID of type usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: support response
          schema:
            $ref: '#/definitions/TypeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single type support based on the ID supplied
      operationId: deleteTypeUsager by id_type_support
      parameters:
        - name: id_type_support
          in: path
          description: ID of type support to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: type support deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  TypeSupport:
    allOf:
      - $ref: '#/definitions/NewTypeSupport'
      - required:
        - id_type_support
        properties:
          id_type_support:
            type: integer
            format: int64
  NewTypeSupport:
    properties:
      libelle_type_support:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string