swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: (Referentiel) Profil agent
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ref_profil_agent:
    get:
      description: |
        Returns all profils agents from the system that the user has access to 
      operationId: findProfilAgent
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: profil agent response
          schema:
            type: array
            items:
              $ref: '#/definitions/ProfilAgent'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new profil agent.
      operationId: addProfilUsager
      parameters:
        - name: profil agent
          in: body
          description: ProfilUsager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewProfilAgent'
      responses:
        200:
          description: profil agent response
          schema:
            $ref: '#/definitions/ProfilAgent'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /ref_profil_agent/{id_profil_agent}:
    get:
      description: Returns an profil agent based on a single ID
      operationId: find profil agent by id_profil_agent
      parameters:
        - name: id_profil_agent
          in: path
          description: ID of profil usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: agent response
          schema:
            $ref: '#/definitions/ProfilAgent'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single profil agent based on the ID supplied
      operationId: deleteProfilUsager by id_profil_agent
      parameters:
        - name: id_profil_agent
          in: path
          description: ID of profil agent to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: profil agent deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ProfilAgent:
    allOf:
      - $ref: '#/definitions/NewProfilAgent'
      - required:
        - id_profil_agent
        properties:
          id_profil_agent:
            type: integer
            format: int64
  NewProfilAgent:
    properties:
      libelle_profil_agent:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string