swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Historique Service
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /historique_service:
    get:
      description: |
        Returns all historique_service's from the system that the user has access to 
      operationId: findHistorique_Service
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: historique_service response
          schema:
            type: array
            items:
              $ref: '#/definitions/HistoriqueService'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new historique_service.
      operationId: addHistoriqueService
      parameters:
        - name: historique_service
          in: body
          description: HistoriqueService to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewHistoriqueService'
      responses:
        200:
          description: historique_service response
          schema:
            $ref: '#/definitions/HistoriqueService'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /historique_service/{id_hs}:
    get:
      description: Returns a historique_service based on a single ID
      operationId: find historique_service by id_hs
      parameters:
        - name: id_hs
          in: path
          description: ID of historique_service to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: historique_service response
          schema:
            $ref: '#/definitions/HistoriqueService'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single historique_service based on the ID supplied
      operationId: deleteHistoriqueService by id_hs
      parameters:
        - name: id_hs
          in: path
          description: ID of historique_service to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: historique_service deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  HistoriqueService:
    allOf:
      - $ref: '#/definitions/NewHistoriqueService'
      - required:
        - id_hs
        properties:
          id_hs:
            type: integer
            format: int64
  NewHistoriqueService:
    properties:
      id_service_hs:
        type: integer
        format: int64
      nom_service_hs:
        type: string
      chapeau_service_hs:
        type: string
      description_service_hs:
        type: string
      logo_service_hs:
        type: string
      telephone_sav_service_hs:
        type: string
      adresse_email_sav_service_hs:
        type: string
      url_espace_client_service_hs:
        type: string
      type_securite_service_hs:
        type: string
      mode_appel_l2_hs:
        type: string
      parametre_l2_hs:
        type: string
      mode_appel_l3_hs:
        type: string
      frequence_appel_l4_hs:
        type: string
      mode_appel_l5_hs:
        type: string
      parametre_l5_hs:
        type: string
      frequence_appel_l5_hs:
        type: string
      frequence_appel_l7_hs:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string