swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Demande support
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /demande_support:
    get:
      description: |
        Returns all demandes supports from the system that the user has access to 
      operationId: findDemandeSupport
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: demande support response
          schema:
            type: array
            items:
              $ref: '#/definitions/DemandeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new demande support.
      operationId: addDemandeSupport
      parameters:
        - name: demande support
          in: body
          description: DemandeSupport to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewDemandeSupport'
      responses:
        200:
          description: demande support response
          schema:
            $ref: '#/definitions/DemandeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /demande_support/{id_demande_support}:
    get:
      description: Returns an demande support based on a single ID
      operationId: find demande support by id_demande_support
      parameters:
        - name: id_demande_support
          in: path
          description: ID of demande support to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: demande support response
          schema:
            $ref: '#/definitions/DemandeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single demande support based on the ID supplied
      operationId: deleteDemandeSupport by id_demande_support
      parameters:
        - name: id_demande_support
          in: path
          description: ID of demande support to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: demande support deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  DemandeSupport:
    allOf:
      - $ref: '#/definitions/NewDemandeSupport'
      - required:
        - id_demande_support
        properties:
          id_support:
            type: integer
            format: int64
  NewDemandeSupport:
    properties:
      date_creation_support:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string