swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Param Batch
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /param_batch:
    get:
      description: |
        Returns all param batch from the system that the user has access to 
      operationId: findParamBatch
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: param batch response
          schema:
            type: array
            items:
              $ref: '#/definitions/ParamBatch'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new param batch.
      operationId: addParamBatch
      parameters:
        - name: param batch
          in: body
          description: ParamBatch to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewParamBatch'
      responses:
        200:
          description: param batch response
          schema:
            $ref: '#/definitions/ParamBatch'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /param_batch/{id_param}:
    get:
      description: Returns an param batch based on a single ID
      operationId: find param batch by id_param
      parameters:
        - name: id_param
          in: path
          description: ID of param batch to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: param batch response
          schema:
            $ref: '#/definitions/ParamBatch'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single param batch based on the ID supplied
      operationId: deleteParamBatch by id_param
      parameters:
        - name: id_param
          in: path
          description: ID of param batch to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: param batch deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  ParamBatch:
    allOf:
      - $ref: '#/definitions/NewParamBatch'
      - required:
        - id_param
        properties:
          id_param:
            type: integer
            format: int64
  NewParamBatch:
    properties:
      libelle_param:
        type: string
      valeur_param:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string