swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: (Referentiel) Type famille
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ref_type_famille:
    get:
      description: |
        Returns all types familles from the system that the user has access to 
      operationId: findTypeFamille
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: type famille response
          schema:
            type: array
            items:
              $ref: '#/definitions/TypeFamille'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new type famille.
      operationId: addTypeUsager
      parameters:
        - name: type famille
          in: body
          description: TypeUsager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewTypeFamille'
      responses:
        200:
          description: type famille response
          schema:
            $ref: '#/definitions/TypeFamille'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /ref_type_famille/{id_type_famille}:
    get:
      description: Returns an type famille based on a single ID
      operationId: find type famille by id_type_famille
      parameters:
        - name: id_type_famille
          in: path
          description: ID of type usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: famille response
          schema:
            $ref: '#/definitions/TypeFamille'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single type famille based on the ID supplied
      operationId: deleteTypeUsager by id_type_famille
      parameters:
        - name: id_type_famille
          in: path
          description: ID of type famille to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: type famille deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  TypeFamille:
    allOf:
      - $ref: '#/definitions/NewTypeFamille'
      - required:
        - id_type_famille
        properties:
          id_type_famille:
            type: integer
            format: int64
  NewTypeFamille:
    properties:
      libelle_type_famille:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string