swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: (Referentiel) Etat support
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ref_etat_support:
    get:
      description: |
        Returns all etats supports from the system that the user has access to 
      operationId: findEtatSupport
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: etat support response
          schema:
            type: array
            items:
              $ref: '#/definitions/EtatSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new etat support.
      operationId: addEtatUsager
      parameters:
        - name: etat support
          in: body
          description: EtatUsager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewEtatSupport'
      responses:
        200:
          description: etat support response
          schema:
            $ref: '#/definitions/EtatSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /ref_etat_support/{id_etat_support}:
    get:
      description: Returns an etat support based on a single ID
      operationId: find etat support by id_etat_support
      parameters:
        - name: id_etat_support
          in: path
          description: ID of etat usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: support response
          schema:
            $ref: '#/definitions/EtatSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single etat support based on the ID supplied
      operationId: deleteEtatUsager by id_etat_support
      parameters:
        - name: id_etat_support
          in: path
          description: ID of etat support to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: etat support deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  EtatSupport:
    allOf:
      - $ref: '#/definitions/NewEtatSupport'
      - required:
        - id_etat_support
        properties:
          id_etat_support:
            type: integer
            format: int64
  NewEtatSupport:
    properties:
      libelle_etat_support:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string