swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Support
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /support:
    get:
      description: |
        Returns all supports from the system that the user has access to 
      operationId: findTypeFamille
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: support response
          schema:
            type: array
            items:
              $ref: '#/definitions/Support'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new support.
      operationId: addSupport
      parameters:
        - name: support
          in: body
          description: Support to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewSupport'
      responses:
        200:
          description: support response
          schema:
            $ref: '#/definitions/Support'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /support/{id_support}:
    get:
      description: Returns an support based on a single ID
      operationId: find support by id_support
      parameters:
        - name: id_support
          in: path
          description: ID of support to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: support response
          schema:
            $ref: '#/definitions/Support'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single support based on the ID supplied
      operationId: deleteSupport by id_support
      parameters:
        - name: id_support
          in: path
          description: ID of support to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: support deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Support:
    allOf:
      - $ref: '#/definitions/NewSupport'
      - required:
        - id_support
        properties:
          id_support:
            type: integer
            format: int64
  NewSupport:
    properties:
      date_fin_support:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string