swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Adhesion
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /adhesion:
    get:
      description: |
        Returns all adhesions from the system that the user has access to 
      operationId: findTypeFamille
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: adhesion response
          schema:
            type: array
            items:
              $ref: '#/definitions/Adhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new adhesion.
      operationId: addAdhesion
      parameters:
        - name: adhesion
          in: body
          description: Adhesion to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewAdhesion'
      responses:
        200:
          description: adhesion response
          schema:
            $ref: '#/definitions/Adhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /adhesion/{id_adhesion}:
    get:
      description: Returns an adhesion based on a single ID
      operationId: find adhesion by id_adhesion
      parameters:
        - name: id_adhesion
          in: path
          description: ID of adhesion to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: adhesion response
          schema:
            $ref: '#/definitions/Adhesion'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single adhesion based on the ID supplied
      operationId: deleteAdhesion by id_adhesion
      parameters:
        - name: id_adhesion
          in: path
          description: ID of adhesion to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: adhesion deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Adhesion:
    allOf:
      - $ref: '#/definitions/NewAdhesion'
      - required:
        - id_adhesion
        properties:
          id_adhesion:
            type: integer
            format: int64
  NewAdhesion:
    properties:
      date_adhesion:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string