swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Liste d'usagers
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /usagers:
    get:
      description: |
        Liste d'usagers
      operationId: findListeUsagers
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: usagers response
          schema:
            type: array
            items:
              $ref: '#/definitions/Usager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates liste d'usagers in the store.
      operationId: addListeUsagers
      responses:
        200:
          description: Usagers response
          schema:
            $ref: '#/definitions/Usager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Usager:
    allOf:
      - $ref: '#/definitions/NewUsager'
      - required:
        - id_usager
        properties:
          id_usager:
            type: integer
            format: int64
  NewUsager:
    properties:
      id_CUT_usager:
        type: integer
        format: int64
      nom_usager:
        type: string
      prenom_usager:
        type: string
      adresse_email_usager:
        type: string
      sexe_usager:
        type: string
      date_naissance_usager:
        type: string
      lieu_naissance_usager:
        type: string
      pays_naissance_usager:
        type: string
      nom_usage_usager:
        type: string
      adresse_postale_usager:
        type: string
      numero_telephone_usager:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string