swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Liste de partenaires
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /partenaire:
    get:
      description: |
        Returns all partenaire from the system that the user has access to 
      operationId: findPartenaire
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: partenaire response
          schema:
            type: array
            items:
              $ref: '#/definitions/Partenaire'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new partenaire.
      operationId: addPartenaire
      parameters:
        - name: partenaire
          in: body
          description: Partenaire to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewPartenaire'
      responses:
        200:
          description: partenaire response
          schema:
            $ref: '#/definitions/Partenaire'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Partenaire:
    allOf:
      - $ref: '#/definitions/NewPartenaire'
      - required:
        - id_partenaire
        properties:
          id_partenaire:
            type: integer
            format: int64
  NewPartenaire:
    properties:
      nom_partenaire:
        type: string
      chapeau_partenaire:
        type: string
      description_partenaire:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string