swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: (Referentiel) Etat usager
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /ref_etat_usager:
    get:
      description: |
        Returns all etats usagers from the system that the user has access to 
      operationId: findEtatUsager
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: etat usager response
          schema:
            type: array
            items:
              $ref: '#/definitions/EtatUsager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new etat usager.
      operationId: addEtatUsager
      parameters:
        - name: etat usager
          in: body
          description: EtatUsager to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewEtatUsager'
      responses:
        200:
          description: etat usager response
          schema:
            $ref: '#/definitions/EtatUsager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /ref_etat_usager/{id_etat_usager}:
    get:
      description: Returns an etat usager based on a single ID
      operationId: find etat usager by id_etat_usager
      parameters:
        - name: id_etat_usager
          in: path
          description: ID of etat usager to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: agent response
          schema:
            $ref: '#/definitions/EtatUsager'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single etat usager based on the ID supplied
      operationId: deleteEtatUsager by id_etat_usager
      parameters:
        - name: id_etat_usager
          in: path
          description: ID of etat usager to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: etat usager deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  EtatUsager:
    allOf:
      - $ref: '#/definitions/NewEtatUsager'
      - required:
        - id_etat_usager
        properties:
          id_etat_usager:
            type: integer
            format: int64
  NewEtatUsager:
    properties:
      libelle_etat_usager:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string