swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Solde
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /solde:
    get:
      description: |
        Returns all soldes from the system that the user has access to 
      operationId: findUsager
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: solde response
          schema:
            type: array
            items:
              $ref: '#/definitions/Solde'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new solde.
      operationId: addSolde
      parameters:
        - name: solde
          in: body
          description: Solde to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewSolde'
      responses:
        200:
          description: solde response
          schema:
            $ref: '#/definitions/Solde'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Solde:
    allOf:
      - $ref: '#/definitions/NewSolde'
      - required:
        - id_solde
        properties:
          id_solde:
            type: integer
            format: int64
  NewSolde:
    properties:
      libelle_solde:
        type: string
      valeur_solde:
        type: string
      lien_solde:
        type: string
      date_creation_solde:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string