swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Famille
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /famille:
    get:
      description: |
        Returns all familles from the system that the user has access to 
      operationId: findFamille
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: famille response
          schema:
            type: array
            items:
              $ref: '#/definitions/Famille'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new famille.
      operationId: addFamille
      parameters:
        - name: famille
          in: body
          description: Famille to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewFamille'
      responses:
        200:
          description: famille response
          schema:
            $ref: '#/definitions/Famille'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /famille/{id_famille}:
    get:
      description: Returns an famille based on a single ID
      operationId: find famille by id_famille
      parameters:
        - name: id_famille
          in: path
          description: ID of famille to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: famille response
          schema:
            $ref: '#/definitions/Famille'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single famille based on the ID supplied
      operationId: deleteFamille by id_famille
      parameters:
        - name: id_famille
          in: path
          description: ID of famille to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: famille deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Famille:
    allOf:
      - $ref: '#/definitions/NewFamille'
      - required:
        - id_famille
  NewFamille:
    properties:
      id_famille:
          type: integer
          format: int64 
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string