swagger: "2.0"
info:
  version: 1.0.0
  title: PassUrbain
  description: Historique DemandeSupport
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /historique_demande_support:
    get:
      description: |
        Returns all historique demande supports from the system that the user has access to 
      operationId: findHistoriqueDemandeSupport
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: historique demande support response
          schema:
            type: array
            items:
              $ref: '#/definitions/HistoriqueDemandeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new historique demande support.
      operationId: addHistoriqueDemandeSupport
      parameters:
        - name: historique demande support
          in: body
          description: HistoriqueDemandeSupport to add to the PU
          required: true
          schema:
            $ref: '#/definitions/NewHistoriqueDemandeSupport'
      responses:
        200:
          description: demande support response
          schema:
            $ref: '#/definitions/HistoriqueDemandeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /historique_demande_support/{id_hds}:
    get:
      description: Returns an historique demande support based on a single ID
      operationId: find historique demande support by id_hds
      parameters:
        - name: id_hds
          in: path
          description: ID of historique demande support to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: historique demande support response
          schema:
            $ref: '#/definitions/HistoriqueDemandeSupport'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single historique demande support based on the ID supplied
      operationId: deleteHistoriqueDemandeSupport by id_hds
      parameters:
        - name: id_hds
          in: path
          description: ID of historique demande support to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: historique demande support deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  HistoriqueDemandeSupport:
    allOf:
      - $ref: '#/definitions/NewHistoriqueDemandeSupport'
      - required:
        - id_hds
        properties:
          id_hds:
            type: integer
            format: int64
  NewHistoriqueDemandeSupport:
    properties:
      date_hds:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string